### ISSUE TITLE
Feature: Pinned list export/import

### ISSUE THREAD

**Issue by Mattie** [Faerbit/persistentpin-webextension#11]
Due to Firefox profile corruption, it'd be great to have an export/import mechanism without having to retype them all in the addons settings. I lost many pins due to these being lost in a corrupted FF storage.

**Comment by Faerbit** [comment]
I'm not quite sure, this in scope for this addon. My Firefox profile never corrupted. Maybe backup your profile?

**Comment by Mattie** [comment]
Importing a list from another server/machine seems at least worthwhile, right?

The reason I love this extension is that even if Firefox's session list gets messed up, your plugin gets my pins back for me. This is just the next level of that-- truly persistent. 

If it's not import/export, but cloud storage/sharing, or recovering a previous pinned list, or similar-- it'd be a great way to grow the addon. It would also be a better way to edit the URLs without the poor experience we currently have in the UI where it's hit or miss there.

Thanks for considering!

**Comment by Faerbit** [comment]
To be quiet honest: I do not have any intention of growing this addon. I created it, because I needed my problem solved. And the current state solves my problem. The last time I looked into changing things, testing changes was quiet a nightmare. So I am little bit reluctant to do that.

I'm open to Pull Requests though ;)
